apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc-config.yaml
  - pvc-books.yaml
  - configmap-seed.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cluster-wide-issuer.yaml
