apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: math-backend-secrets
spec:
  provider: azure
  secretObjects:
    - secretName: math-backend-db
      type: Opaque
      data:
        - objectName: postgres-connection-string
          key: DATABASE_URL
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "abfd7494-4b44-4768-b9f3-947b351bc64c"
    keyvaultName: kv-books-dev-9k0m5p
    tenantId: "131e4e3f-2a8a-4cea-85de-a2273fb3d2ab"
    objects: |
      array:
        - |
          objectName: postgres-connection-string
          objectType: secret
