apiVersion: v1
kind: ServiceAccount
metadata:
  name: math-backend
  annotations:
    azure.workload.identity/client-id: "abfd7494-4b44-4768-b9f3-947b351bc64c"
  labels:
    azure.workload.identity/use: "true"
